version: "3.3"

services:
  apisvr:
    container_name: testapi
    env_file: ./variables.env
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - PORT=${PORT}
    ports:
      - "8001:8000"
    restart: always
    tty: true
